// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAYmB7yZyrhWMH6h2UEruOSxlB1LuNhus',
    appId: '1:262359544294:web:db54f2a338ded6ca79e627',
    messagingSenderId: '262359544294',
    projectId: 'sharemeal-47aac',
    authDomain: 'sharemeal-47aac.firebaseapp.com',
    storageBucket: 'sharemeal-47aac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv3ujC8XLncj4zHsWTwiR_drtykEiwNQA',
    appId: '1:262359544294:android:cac4f6ea5d0cead079e627',
    messagingSenderId: '262359544294',
    projectId: 'sharemeal-47aac',
    storageBucket: 'sharemeal-47aac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCczSwwr_Gpteqy5WGEJu_yJHjjw7S6yfs',
    appId: '1:262359544294:ios:7a7a0f0b49566e3e79e627',
    messagingSenderId: '262359544294',
    projectId: 'sharemeal-47aac',
    storageBucket: 'sharemeal-47aac.firebasestorage.app',
    iosClientId: '262359544294-urr20sjm6ej046jbh47omjq6fa1c9jdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharemeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAYmB7yZyrhWMH6h2UEruOSxlB1LuNhus',
    appId: '1:262359544294:web:ab47f9df465fa3bf79e627',
    messagingSenderId: '262359544294',
    projectId: 'sharemeal-47aac',
    authDomain: 'sharemeal-47aac.firebaseapp.com',
    storageBucket: 'sharemeal-47aac.firebasestorage.app',
  );
}
