import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'package:sharemeal/firebase_options.dart';        // auto-generated by flutterfire configure
import 'package:sharemeal/models/app_state.dart';
import 'package:sharemeal/screens/auth_wrapper.dart';    // our new smart first screen
import 'package:sharemeal/constants/app_theme.dart';

void main() async {
  // Ensures Flutter is ready before we do anything
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase — MUST happen before runApp()
  // DefaultFirebaseOptions.currentPlatform automatically picks
  // the right config for Android / iOS / Web
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Status bar styling (same as before)
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor:          Colors.transparent,
    statusBarIconBrightness: Brightness.light,
    statusBarBrightness:     Brightness.dark,
  ));

  runApp(
    ChangeNotifierProvider(
      create: (_) => AppState(),
      child: const ShareMealApp(),
    ),
  );
}

class ShareMealApp extends StatelessWidget {
  const ShareMealApp({super.key});

  @override
  Widget build(BuildContext context) {
    final appState = Provider.of<AppState>(context);

    return MaterialApp(
      title:                      'ShareMeal',
      debugShowCheckedModeBanner: false,
      theme:                      AppTheme.light,
      darkTheme:                  AppTheme.dark,
      // Login screen always uses light theme, dashboards respect theme setting
      themeMode: appState.isDarkMode ? ThemeMode.dark : ThemeMode.light,
      home: const AuthWrapper(),   // 👈 AuthWrapper handles routing
    );
  }
}